[package]
name = "cf-ddns"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
regex = "1.8.4"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde_json = "1.0.99"
